### ISSUE TITLE
Deployment of flux-ros-hadoop on kubernet cluster

### ISSUE THREAD

**Issue by Deepak3994** [flux-project/flux#16]
I am getting the following error,

NAME                                                         READY     STATUS               RESTARTS     AGE
pod/flux-ros-hadoop-5f8cd4bc67-h5thl          0/1       ImagePullBackOff          0              45m

It not in the running state. May I know where I have went wrong?

**Comment by Deepak3994** [comment]
This is regarding the issue which I have posted recently in the same trailing mail.

![screenshot_2018-08-06 overview - kubernetes dashboard](https://user-images.githubusercontent.com/20994657/43701874-7943c5a2-9975-11e8-95e0-4e2cf666396a.png)

The above image is a screenshot from  the kubernet dash board.

**Comment by Deepak3994** [comment]
Is the image fluxproject/examples is present in docker hub?

**Comment by Karthikeya108** [comment]
Hello,

fluxproject/examples is available in docker hub. Can you provide more information on which environment are you deploying this ?  Standalone machine / Cloud and OS, Docker and Kubernetes version  etc.

**Comment by Deepak3994** [comment]
Currently I am running on standalone machine using vm's. Have created kubernetes cluster in Ubuntu.
Dedicated each VM, 100GB of space, 4GB of ram and 2 CPU cores.

**Kubernet Version:** 
_Client Version:_ version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
_Server Version:_ version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Docker version:**
_Client:_
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.6.2

**Comment by Deepak3994** [comment]
Any updates on the previous threads...

**Comment by Deepak3994** [comment]
Hi Karthikeya,

I am waiting for your reply for the above problem.

**Comment by Deepak3994** [comment]
Hi,

I tried executing "./bin/flux pull" command. The docker image "fluxproject/flux" gets pulled successfully but the docker image "fluxproject/examples" gives an error, which I have pasted below.

**Error response from daemon: manifest for fluxproject/examples:latest not found**

I have checked the docker hub, there the "fluxproject/example" image is available. So i tried pulling it manually still I am getting the same error.

**Comment by Deepak3994** [comment]
I have one query. I was going through the "**flux-project/flux**" repo. I cam across a folder name "distributed" in the path "**/deploy/kubernetes/distributed/**" which consists of followinf files
- hdfs-flux
- hdfs-pv
- hdfs-pvc
- flux
- flux-init

Can anyone, kindly brief me out on what are the uses of these folders and where we need to use?

Because I have not seen these folders being used in the docker files.

**Comment by Karthikeya108** [comment]
Hello,

This is an additional feature to support deployment of HDFS in distributed mode (on multiple machines) with data persistence. This is not yet integrated into the main setup. Nevertheless you can try it out.

Please look at the README.md file in the following location
https://github.com/flux-project/flux/tree/master/deploy/kubernetes/distributed

**Comment by Deepak3994** [comment]
Hi,

I was waiting for your reply kindly help us for the below issue. 
I am running on standalone machine using vm's. Have created kubernetes cluster in Ubuntu.
Dedicated each VM, 100GB of space, 4GB of ram and 2 CPU cores.

Kubernet Version:
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

Docker version:
Client:
Version: 17.03.2-ce
API version: 1.27
Go version: go1.6.2

**Comment by Deepak3994** [comment]
Hi Karthikeya,

I was going through the YAML file in the kubernetes folder under deploy.

spec:
      containers:
      - image: **fluxproject/examples_gpu**
        imagePullPolicy: IfNotPresent
        name: flux-ros-hadoop-gpu
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: 
          limits:
            **nvidia.com/gpu: 1**
          requests:
             **nvidia.com/gpu: 1**


I have two questions here which i have highlighted,
1) Is it possible to get the docker file of "fluxproject/examples_gpu"? (In dockerhub i couldnt find its dockerfile).
2) There is a key named as "resources". What does the limits and requests actually refers to? For ex: I have two nvidia cards in one system. So how should i mention that here?

**Comment by Karthikeya108** [comment]
Hi Deepak,

Could you please confirm if the primary issue that you reported in this ticket is fixed ?
Please create a different ticket for different issues with a relevant issue name and description.

**Comment by Deepak3994** [comment]
Hi Kathikeya,

**I did "./bin/flux build"**

Its getting stuck at this point,

  Running setup.py install for configparser: started
    Running setup.py install for configparser: finished with status 'done'
  Found existing installation: defusedxml 0.4.1
**Cannot uninstall 'defusedxml'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.**
The command '/bin/sh -c python2 -m pip install --upgrade --user pip &&     python3 -m pip install --upgrade --user pip &&     python3 -m pip install --no-cache-dir --upgrade jupyter jupyterhub jupyterlab &&     python2 -m pip install --no-cache-dir --upgrade pyspark matplotlib pandas tensorflow keras Pillow &&     python2 -m pip install --no-cache-dir --upgrade --force-reinstall requests imageio moviepy seaborn gmaps &&     python2 -m pip install ipykernel &&     python2 -m ipykernel install &&     python3 -m pip install ipykernel &&     python3 -m ipykernel install' **returned a non-zero code: 1**


Do you know why this is happening?

**Comment by Karthikeya108** [comment]
Hi Deepak,

I am not able to reproduce this issue. Could you pull the latest version of the repo and try again ?

**Comment by Deepak3994** [comment]
Hi Karthikeya,

Yea.
Sorry about that, I resolved that issue.
Latest repo i had pulled. There was some dependencie issue with "defusedxml", which i removed and now everything is working fine.
